### ISSUE TITLE
逻辑回归中代价函数的梯度下降表示有误

### ISSUE THREAD

**Issue by zg9uagfv** [ysh329/Chinese-UFLDL-Tutorial#29]
逻辑回归最后的梯度下降表示有误,
原表达式：
$$
\frac{\partial J(\theta)}{\partial \theta_{j}} = \sum_{i}x_{j}^{(i)} \left ( h_{\theta}(x^{(i)} - y^{(i)} )  \right ). 
$$  
应该改为
$$
\frac{\partial J(\theta)}{\partial \theta_{j}} = \sum_{i}x_{j}^{(i)} \left ( h_{\theta}(x^{(i)}) - y^{(i)}   \right ). 
$$

**Comment by ysh329** [comment]
Thanks my big brother. I think my translated tutorial is not good enough to help others, especially for those new guys. Thus, I recommend CS231n as a start tutorial for you or other new guys. Of course, this course has an Chinese version on study.163.com.

**Comment by ysh329** [comment]
Fixed. Great thanks! 🤣
