### ISSUE TITLE
softmax回归中的笔误

### ISSUE THREAD

**Issue by zg9uagfv** [ysh329/Chinese-UFLDL-Tutorial#30]
$$
\begin{align}
h(x) &=

\frac{1}{ \exp( (\theta^{(1)}-\theta^{(2)})^\top x^{(i)} ) + \exp(\vec{0}^\top x) }
\begin{bmatrix}
\exp( (\theta^{(1)}-\theta^{(2)})^\top x ) 
\exp( \vec{0}^\top x ) \\
\end{bmatrix} \\
$$

应该改为
$$
\begin{align}
h(x) &=

\frac{1}{ \exp( (\theta^{(1)}-\theta^{(2)})^\top x^{(i)} ) + \exp(\vec{0}^\top x) }
\begin{bmatrix}
\exp( (\theta^{(1)}-\theta^{(2)})^\top x ) \\
\exp( \vec{0}^\top x ) \\
\end{bmatrix} \\
$$

**Comment by ysh329** [comment]
@zg9uagfv Thanks my big brother. I think my translated tutorial is not good enough to help others, especially for those new guys. Thus, I recommend [CS231n](cs231n.github.io) as a start tutorial for you or other new guys. Of course, this course has an [Chinese version](http://study.163.com/course/courseMain.htm?courseId=1003223001) on study.163.com.
